# Generated by Django 3.1.3 on 2020-12-21 05:02

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_authsms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authsms',
            name='id',
        ),
        migrations.AddField(
            model_name='authsms',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='authsms',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='authsms',
            name='auth_number',
            field=models.IntegerField(verbose_name='인증번호'),
        ),
        migrations.AlterField(
            model_name='authsms',
            name='phone_number',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='휴대폰번호'),
        ),
    ]
