# Generated by Django 3.1.3 on 2020-12-28 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201221_1402'),
        ('user', '0002_user_kakao_id'),
    ]

    operations = [
    ]
